name: wordle

channels:
    - conda-forge
    - defaults

dependencies:
    - black
    - emoji
    - flake8>=3.7.9
    - ipdb
    - ipykernel
    - mypy>=0.740
    - nltk
    - numpy>=1.18
    - pip>=20.0
    - python=3.9
